### ISSUE TITLE
Does not respect configured twig rules

### ISSUE THREAD

**Issue by devbanana** [biati-digital/nova-php-cs-fixer#15]
**Describe the bug**

I have set rules in the Twig rules option, both in the main extension options and in the project settings, and neither are used when formatting Twig.

I looked at the source and it looks like even though it uses config.twigrules in the constructor of TwigFormatter (see [line 16](https://github.com/biati-digital/nova-php-cs-fixer/blob/56a73d1971fec1cade383e70be2fd2f5b5f7653e/Scripts/formatter-twig.js#L16)), it never actually uses those rules.

**Post an example code**

These are options I set in the twig rules option:

indent_level: 0
new_line: true
preserve: 1

In particular the indent_level option is always set at 2 even though I'd like it at 0.

**Expected behavior**

It should use the options I configure in the Twig rules option.

**Comment by biati-digital** [comment]
Hi @devbanana you are right, sorry about that, i don't use twig so i used the default prettydiff rules and somehow i forgot about the user rules.

I'm working on an update to fix this and some other changes

**Comment by biati-digital** [comment]
This has been fixed in v4 [View Changelog](https://github.com/biati-digital/nova-php-cs-fixer/blob/main/phpcsfixer.novaextension/CHANGELOG.md) Please try it and let me know if it's working for you.
