### ISSUE TITLE
Twig line whitespace trimming modifier

### ISSUE THREAD

**Issue by brucep** [biati-digital/nova-php-cs-fixer#16]
The `~` modifier used for [line whitespace trimming](https://twig.symfony.com/doc/3.x/templates.html#whitespace-control) is incorrectly formatted; a space is added between the modifier and the tag.

Maybe it's being confused with the [concatenation operator](https://twig.symfony.com/doc/3.x/templates.html#other-operators)?

**Comment by biati-digital** [comment]
Closing as no more info was provided
