### ISSUE TITLE
CRITICAL Bug WITH path working

### ISSUE THREAD

**Issue by GandjaFuzz** [biati-digital/nova-php-cs-fixer#17]
Have paths: 
/api/main/23/RC_Api.php
/api/main/22/RC_Api.php
/api/main/21/RC_Api.php
/api/main/20/RC_Api.php
/api/main/19/RC_Api.php

all files differents. 
but if I fast save all files in debug area generate 1 path of all files -> apimainrcapi.php
numbers ignored. 
and random 1 files replace others files. 
fore example 19 api replace files 20 21 22 23

**Comment by biati-digital** [comment]
Please use the correct template for bug reports, and explain your issue correctly, i do not understand anything you said, there's no context for me to understand what are you doing and what's happening.

Open a new issue using the correct template.
