### ISSUE TITLE
CRITICAL bug with path generate for PHPCsFixer

### ISSUE THREAD

**Issue by GandjaFuzz** [biati-digital/nova-php-cs-fixer#18]
**Describe the bug**
I have this tree on php project
Project/Api/Main/13/Api.php
Project/Api/Main/14/Api.php
Project/Api/Main/15/Api.php
Project/Api/Main/16/Api.php
Project/Api/Main/17/Api.php
Project/Api/Main/18/Api.php
Project/Api/Main/19/Api.php
Project/Api/Main/20/Api.php

when I format php files in same time for all files in tree generate this 1 path: 
> PHP CS Fixer[13:40:08.978000]    1) /Users/kingsman/Library/Application Support/Nova/Workspaces/F66C4A38-1406-4107-8697-60AFA81B7B28/biati.phpcsfixer/projectapimainapi.php 
> 
> Fixed all files in 22.872 seconds, 24.000 MB memory used

and data randomly mix between each other because when generate this name - projectapimainapi.php, you skip all numbers from path for generate this name

**Comment by biati-digital** [comment]
Hi, the issue template is there because it helps me understand and even replicate the issue, your text does not tell me anything and literally makes no sense.

PHP CS Fixer only fixes the current file, if you save "projectapimainapi.php" only that file is formatted, it does not format or modify any other files in your project tree. Also this extension does not modify files directly, everything is handled by Nova.

i've no idea what this means "_you skip all numbers from path for generate this name_"

Can you maybe provide a video recording? anything that helps me understand what's happening here.

**Comment by GandjaFuzz** [comment]
you generate temporary name for php cs fixer from path original file from project.

this path: Project/Api/Main/20/Api.php should be generated ProjectApiMain20Api.php, but you generate ProjectApiMainApi.php
and when I do replace string from all files in project all files auto save with formatter. BUT for all files generate 1 path

Project/Api/Main/13/Api.php -> ProjectApiMainApi.php
Project/Api/Main/14/Api.php -> ProjectApiMainApi.php
Project/Api/Main/15/Api.php -> ProjectApiMainApi.php
Project/Api/Main/16/Api.php -> ProjectApiMainApi.php
Project/Api/Main/17/Api.php -> ProjectApiMainApi.php
Project/Api/Main/18/Api.php -> ProjectApiMainApi.php
Project/Api/Main/19/Api.php -> ProjectApiMainApi.php
Project/Api/Main/20/Api.php -> ProjectApiMainApi.php

but need 

Project/Api/Main/13/Api.php -> ProjectApiMain13Api.php
Project/Api/Main/14/Api.php -> ProjectApiMain14Api.php
Project/Api/Main/15/Api.php -> ProjectApiMain15Api.php
Project/Api/Main/16/Api.php -> ProjectApiMain16Api.php
Project/Api/Main/17/Api.php -> ProjectApiMain17Api.php
Project/Api/Main/18/Api.php -> ProjectApiMain18Api.php
Project/Api/Main/19/Api.php -> ProjectApiMain19Api.php
Project/Api/Main/20/Api.php -> ProjectApiMain20Api.php

**Comment by GandjaFuzz** [comment]
https://user-images.githubusercontent.com/14003794/145210450-c40fbdb2-1c4e-4641-9639-85979af11bdd.mov

**Comment by biati-digital** [comment]
Ok, thank you for the info.

Saving a lot of files at the same **and having that specific project structure** will overwrite the temporary file if the process does not end quickly.

I'll fix this asap.

**Comment by GandjaFuzz** [comment]
thank you so much

**Comment by GandjaFuzz** [comment]
hello when you can fix this ?

**Comment by biati-digital** [comment]
This has been fixed in 4.0.2, update it from the extensions library.
