### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by igorkiselev** [biati-digital/nova-php-cs-fixer#19]
**Describe the bug**
When saving, the file is scrolled to the beginning

**Expected behavior**
It would be great if the code was fixed, but the scrolling remained in the place where you are working now.

**Comment by biati-digital** [comment]
Make sure you are using the latest version of Nova, they introduced a bug in a previous version, see the closed issues.

Nova is the one that maintains the scroll position after the text is formatted (this is not handled by the extension), but as for now (like many other parts of Nova) it's not perfect.
