### ISSUE TITLE
PSR-12

### ISSUE THREAD

**Issue by BenjaminHoegh** [biati-digital/nova-php-cs-fixer#2]
https://github.com/FriendsOfPHP/PHP-CS-Fixer/pull/4943

**Comment by biati-digital** [comment]
PSR-12 ruleset merged into php-cs-fixer 2.18, please update the extension to use the latest version of php-cs-fixer and then you can select the standard in the extension preferences

![CleanShot 2021-03-17 at 02 17 05](https://user-images.githubusercontent.com/1219228/111435843-e9daa880-86c6-11eb-868d-0a397b9835ca.png)
