### ISSUE TITLE
Setting wrong class name

### ISSUE THREAD

**Issue by LucaRossi77** [biati-digital/nova-php-cs-fixer#23]
**Describe the bug**
The extension is always overwriting the class name with a wrong one.
If I launch php cs fixer with my settings from the console it's all correct

**Post an example code**
The file name is User.php

Before php cs fixer 

`namespace App\Models;

class User extends Authenticatable`

After php cs fixer

`namespace App\Models;

class appmodelsuser extends Authenticatable`

I think the problem is due to the copy and renaming of the file in the cache directory, and php cs fixer is launched against the renamed file, which is at this point appmodelsusers.php. I append a log of the execution

`PHP CS Fixer[14:57:01.661000] temp file created in

PHP CS Fixer[14:57:01.661000] /Users/lucarossi/Library/Application Support/Nova/Workspaces/ECB4336E-9D9A-469D-98FD-5879482BFE4B/biati.phpcsfixer/appmodelsuser.php

PHP CS Fixer[14:57:01.662000] Using existing cache file

PHP CS Fixer[14:57:01.662000] Cache file path is /Users/lucarossi/Library/Application Support/Nova/Extensions/biati.phpcsfixer/php/.php-cs-fixer.cache

PHP CS Fixer[14:57:01.662000] Generated command to fix file

PHP CS Fixer[14:57:01.663000] /opt/homebrew/bin/php /opt/homebrew/bin/php-cs-fixer fix /Users/lucarossi/Library/Application Support/Nova/Workspaces/ECB4336E-9D9A-469D-98FD-5879482BFE4B/biati.phpcsfixer/appmodelsuser.php --config=/Users/lucarossi/code/1hs/.php-cs-fixer.php --using-cache=yes --cache-file=/Users/lucarossi/Library/Application Support/Nova/Extensions/biati.phpcsfixer/php/.php-cs-fixer.cache`

**Expected behavior**
The class name should stay User

**Comment by biati-digital** [comment]
Not able to replicate, please check your rules. 

Before formatting
![CleanShot 2022-04-12 at 21 08 42](https://user-images.githubusercontent.com/1219228/163085627-51406d4b-9cdb-4bbe-97e9-551e2cd81d4e.png)

// After formatting
![CleanShot 2022-04-12 at 21 08 52](https://user-images.githubusercontent.com/1219228/163085649-47a6ce45-d1ba-4b18-880d-1f94b61ed99a.png)
 
Please note, my license already expired and i went back to  php storm, i'm afraid i can not provide much help with this.
