### ISSUE TITLE
Additional } added at save time.

### ISSUE THREAD

**Issue by bugcafe** [biati-digital/nova-php-cs-fixer#3]
When there is a gap between the end of code and the closing } an additional }  is added rather than bringing the }  up to the preceding code. 

See examples below:

Before save:
<img width="867" alt="Screen Shot 2020-10-26 at 10 54 52 AM" src="https://user-images.githubusercontent.com/3015472/97122441-f2632e80-1779-11eb-8d5e-daa3763be69d.png">

After Save:
<img width="857" alt="Screen Shot 2020-10-26 at 10 55 51 AM" src="https://user-images.githubusercontent.com/3015472/97122447-fa22d300-1779-11eb-9fe5-3554dbf683a5.png">

**Comment by biati-digital** [comment]
Can you please share that code so i can make some tests? does it happens always? If you disable "Format HTML in PHP files" and "Apply additional fixes" in the extension preferences does it continue to happen?

**Comment by biati-digital** [comment]
Closing as no more information was provided and i'm sure the problem was with another extension "Prettier"
