### ISSUE TITLE
php 8.2 php-cs-fixer 3.16.0 

### ISSUE THREAD

**Issue by GandjaFuzz** [biati-digital/nova-php-cs-fixer#30]
PHP CS Fixer 3.16.0 (d40f943) BoY42 by Fabien Potencier and Dariusz Ruminski.
PHP runtime: 8.2.4

not apply formatted file
when save file temporary file good formatted but it is not apple in editor. 
get error:
PHP CS Fixer[0:54:32.240000] Formatting process error

in new version just change log
PHP CS Fixer[0:54:32.240000] PHP formatted in process took 328ms

PHP CS Fixer[0:54:32.240000]    1) /Users/kingsman/Library/Application Support/Nova/Workspaces/F66C4A38-1406-4107-8697-60AFA81B7B28/biati.phpcsfixer/engineclassespubliccontrollerspcmobileapps.php

Fixed 1 of 1 files in 0.252 seconds, 18.000 MB memory used

PHP CS Fixer[0:54:32.240000] stdOut.length = 3
PHP CS Fixer[0:54:32.240000] stdOut    
1) /Users/kingsman/Library/Application Support/Nova/Workspaces/F66C4A38-1406-4107-8697-60AFA81B7B28/biati.phpcsfixer/engineclassespubliccontrollerspcmobileapps.php

Fixed 1 of 1 files in 0.252 seconds, 18.000 MB memory used

PHP CS Fixer[0:54:32.240000] stdErr.length = 2
PHP CS Fixer[0:54:32.240000] stdErr 
Loaded config default.
Using cache file "/Users/kingsman/Library/Application Support/Nova/Extensions/biati.phpcsfixer/php/.php-cs-fixer.cache".

PHP CS Fixer[0:54:32.240000] Formatting process error

PHP CS Fixer[0:54:32.240000] Loaded config default.
 Using cache file "/Users/kingsman/Library/Application Support/Nova/Extensions/biati.phpcsfixer/php/.php-cs-fixer.cache".

**Comment by GandjaFuzz** [comment]
For fix this can change

this
`} else if (stdOut && stdOut.join('').includes('Fixed all files')) {`
on this
`} else if (stdOut && (stdOut.join('').includes('Fixed all files') || stdOut.join('').includes('Fixed 1 of 1 files'))) {`

**Comment by moskoweb** [comment]
I came up with the same solution to solve the slowness problem I was having with me.

https://github.com/biati-digital/nova-php-cs-fixer/pull/32

**Comment by biati-digital** [comment]
A new update has been published 4.3.1, both formatting methods should work (using a dedicated server or a Nova Process) please try it and let me know if it's working for you.
