### ISSUE TITLE
indent_size not working

### ISSUE THREAD

**Issue by Babelfisch** [biati-digital/nova-php-cs-fixer#4]
I try to set `indent_size: 4` in the global config but it has no effect. All PHP code will be indented with 2 characters. It works only in the HTML config section and HTML code.

It would be great, if you could fix this for PHP code or – better – read the Nova configuration and use the selected editor tab width.

**Comment by biati-digital** [comment]
i'm 100% sure this is not a problem with the extension, i use an indent size of 4 (thats the standard) and never had a problem with PHP or HTML, also the extension has more than 800 installations right now and this is the first time i heard this. Could you please share a screenshot of your config? also did you try to relaunch nova?

**Comment by biati-digital** [comment]
Closing as not more info was provided
