### ISSUE TITLE
First line indent in mixed html / php content

### ISSUE THREAD

**Issue by dna75** [biati-digital/nova-php-cs-fixer#6]
When I have a mixed html / php content file I notice that the first PHP line indent is wrong.
If the PHP code is placed between HTML tags the first line indent of the PHP code is wrong.

**Comment by biati-digital** [comment]
Hi, please post an example code so I can copy paste and make the required tests

**Comment by dna75** [comment]
`<html>

<head>
    <link rel="stylesheet" href="your.css" title="CSS Title" type="text/css" media="screen" charset="utf-8">
</head>

<body>
    <?php
echo 'Nova';
if (isset($panic)) {
    echo 'No';
} else {
    echo 'blah blah';
}
?>
</body>

</html>`

**Comment by biati-digital** [comment]
Thank's 'll check the file, I'm preparing an update so I hope to get this fix included.

**Comment by biati-digital** [comment]
I've published an update and this issue should be fixed. Make sure to enable "Apply additional fixes", please try it and let me know if it's working for you.

![CleanShot 2021-01-21 at 18 54 36](https://user-images.githubusercontent.com/1219228/105430887-2daab780-5c1a-11eb-8e02-28c2276788ee.png)

![CleanShot 2021-01-21 at 18 53 34](https://user-images.githubusercontent.com/1219228/105430913-3dc29700-5c1a-11eb-88c3-7cff68bcf1d9.gif)

**Comment by dna75** [comment]
Thanks! That fixed the issue!
