### ISSUE TITLE
issue with php balise

### ISSUE THREAD

**Issue by BenoitBruyere** [biati-digital/nova-php-cs-fixer#7]
Hi, 

when I save this part of code:
```
<script type="text/javascript">
   <?php
```
the opening php become '< ? php'.

How to fix this issue please?

Best regards

**Comment by biati-digital** [comment]
Hi, please post an example code so I can copy paste and make the required tests

**Comment by BenoitBruyere** [comment]
for exemple 
```
<script type="text/javascript">
<?php
echo "alert('test')";

?>
</script>
```

become after save 
```
<script type="text/javascript">
< ? php
echo "alert('test')"; 
?
>
</script>

```

**Comment by biati-digital** [comment]
This should be fixed in the latest version, can you please try it and let me know if it's working for you?
