### ISSUE TITLE
Breaks blade comments

### ISSUE THREAD

**Issue by Elwood-P** [biati-digital/nova-php-cs-fixer#8]
Extension breaks blade comments by erroneously adding a space in the middle of the opening and closing markers:

`{{-- This is a comment --}}`

Changes to:
`{{ -- This is a comment -- }}`

**Comment by biati-digital** [comment]
Thanks for the report, we'll fix it and publish an update today or tomorrow.

**Comment by biati-digital** [comment]
So I submitted an update "2.0.3" that fixes this issue, while doing the update Nova returned errors about connection timeout to the extensions server, and more errors, until the last I error was that 2.0.3 was already published, I'm not able to see the update, can you please check if you see an available update in the extensions library?

**Comment by Elwood-P** [comment]
Perfect tx. Updated to 2.0.4 fixed the issue.
